---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quote_server
  template:
    metadata:
      labels:
        app: quote_server
    spec:
      containers:
        - name: quote_server
          image: quote_server
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
          env:
            - name: API_KEY
              value: "12345"
