apiVersion: v1
kind: Service
metadata:
  name: app-service-prod
spec:
  selector: #Label selector and environment are very important
    app: quote_server_prod
    environment: production
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 3000
  type: LoadBalancer
