apiVersion: v1
kind: Service
metadata:
  name: app-service_dev
spec:
  selector:
    app: quote_server_dev
    environment: development
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: app-service_prod
spec:
  selector:
    app: quote_server_prod
    environment: production
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 3000
  type: LoadBalancer
