apiVersion: v1
kind: Service
metadata:
  name: app-service-dev
spec:
  selector:
    app: quote_server_dev
    environment: development
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
