name: Status Check

on:
  pull_request:
    branches:
      - main
      - releasebranch

jobs:
  status_check:
    runs-on: self-hosted
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v43 #https://github.com/marketplace/actions/changed-files

      - name: List all changed files
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        run: |
          for file in ${ALL_CHANGED_FILES}; do
          echo "$file was changed"
          done

      - name: List the commit SHA
        run: |
          echo "The commit SHA that triggered this workflow is: $GITHUB_SHA"
          git_hash=$(git rev-parse --short "$GITHUB_SHA")
          echo "The shortened hash is: $git_hash"
