name: Status Check

on:
  pull_request:
    branches:
      - main
      - releasebranch

jobs:
  status_check:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 #GitHub actions default checkout

      - name: Check git diff #checks which files have been changed in current commit
        run: |
          HEAD=${{ github.event.pull_request.head.ref }}
          BASE=${{ github.event.pull_request.base.ref }}
          echo "Pull Request Base Ref: ${{ github.event.pull_request.base.ref }}"
          echo "Pull Request Head Ref: ${{ github.event.pull_request.head.ref }}"
          HASH=$(git merge-base ${HEAD} ${BASE})
          CHANGES=$(git diff --name-only --diff-filter=A ${HASH} ${HEAD})
          echo $CHANGES